'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { BadgeCheck, BarChart3, Edit3, Link2, QrCode, Rocket, Ticket } from 'lucide-react';
import AuthGate from '@/components/AuthGate';
import { loadEventsFromSupabase, saveEventToSupabase } from '@/lib/supabase-events';
import { Event } from '@/lib/types';

function AdminEventsContent(){
 const [events,setEvents]=useState<Event[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function load(){setLoading(true); const result=await loadEventsFromSupabase(); setEvents(result.events); setError(result.ok?'':result.error??'No se pudieron cargar eventos.'); setLoading(false)}
 useEffect(()=>{load();},[]);
 async function toggle(id:string){const next=events.map(e=>e.id===id?{...e,status:e.status==='published'?'unpublished':'published'} as Event:e); setEvents(next); const event=next.find(e=>e.id===id); if(event){const result=await saveEventToSupabase(event); if(!result.ok&&!result.skipped) setError(result.error??'No se pudo actualizar estado.')}}
 return <section className="container-page py-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-semibold text-red-300">Productor</p><h1 className="text-4xl font-black text-white">Mis eventos</h1><p className="mt-2 text-white/65">Eventos reales desde Supabase: funciones, tickets/e-tickets, ventas, RRPP y acreditación.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={load}>Actualizar</button><Link className="btn-primary" href="/admin/eventos/nuevo">Nuevo evento</Link></div></div>{error&&<div className="mt-6 rounded-2xl border border-red-300/30 bg-red-950/40 p-4 text-sm text-red-100">{error}</div>}{loading&&<div className="mt-8 card p-6 text-white/70">Cargando eventos reales desde Supabase...</div>}<div className="mt-8 overflow-hidden rounded-3xl border border-white/15 bg-white/5 backdrop-blur"><table className="w-full min-w-[1040px] text-sm text-white"><thead className="bg-white/10 text-left text-white/75"><tr><th className="p-4">Evento</th><th className="p-4">Estado</th><th className="p-4">Capacidad</th><th className="p-4">Acciones rápidas</th></tr></thead><tbody>{events.map(e=><tr key={e.id} className="border-t border-white/10 align-top hover:bg-white/5"><td className="p-4"><p className="font-black text-white">{e.name}</p><p className="mt-1 text-white/55">{e.venue||'Lugar a confirmar'}</p><p className="mt-1 text-xs text-white/40">{e.ticketTypes.length} tipos de entrada · {e.dates.length} función/es</p></td><td className="p-4"><span className="badge">{e.status}</span></td><td className="p-4 font-bold text-white/80">{e.capacity}</td><td className="p-4"><div className="flex flex-wrap gap-2"><Link className="btn-secondary" href={`/admin/eventos/${e.id}`}><Edit3 size={16} className="mr-2"/>Editar</Link><button className="btn-secondary" onClick={()=>toggle(e.id)}><Rocket size={16} className="mr-2"/>{e.status==='published'?'Despublicar':'Publicar'}</button><Link className="btn-secondary" href={`/admin/tickets?eventId=${e.id}`}><Ticket size={16} className="mr-2"/>Tickets</Link><Link className="btn-primary" href={`/admin/tickets?eventId=${e.id}&action=create-eticket`}><QrCode size={16} className="mr-2"/>Crear e-ticket</Link><Link className="btn-secondary" href="/admin/rrpp"><Link2 size={16} className="mr-2"/>RRPP</Link><Link className="btn-secondary" href="/scanner"><BadgeCheck size={16} className="mr-2"/>Acreditar</Link><Link className="btn-secondary" href="/admin/reportes"><BarChart3 size={16} className="mr-2"/>Reportes</Link></div></td></tr>)}{!loading&&!events.length&&<tr><td colSpan={4} className="p-6 text-white/60">Todavía no hay eventos productivos cargados.</td></tr>}</tbody></table></div></section>
}
export default function AdminEventsPage(){return <AuthGate allow={['super_admin','admin','producer']}><AdminEventsContent/></AuthGate>}
