'use client';

import { useEffect, useState } from 'react';
import AuthGate from '@/components/AuthGate';
import { createBrowserSupabaseClient } from '@/lib/supabase';
import { roleLabels, rolePermissions, type Permission, type PlatformRole } from '@/lib/platform-config';

const permissions: Permission[] = ['events.manage_all','events.manage_own','sales.view_all','sales.view_own','sales.view_rrpp','service_fees.manage','users.manage','tickets.validate','reports.export','links.manage_own'];
const roles = Object.keys(roleLabels) as PlatformRole[];

type Assignment = { profile_id:string; role:PlatformRole; producer_id?:string|null; active:boolean; profile?:{full_name?:string|null}; producer?:{name?:string|null} };

function RolesContent(){
 const [assignments,setAssignments]=useState<Assignment[]>([]);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState('');
 useEffect(()=>{async function load(){const supabase=createBrowserSupabaseClient(); if(!supabase){setError('Falta configurar Supabase.'); setLoading(false); return;} const {data}=await supabase.auth.getSession(); if(!data.session){setError('Sesión vencida. Volvé a ingresar.'); setLoading(false); return;} const [{data:profiles,error:profilesError},{data:members,error:membersError}]=await Promise.all([supabase.from('profiles').select('id,full_name,role,active').eq('active',true),supabase.from('producer_members').select('profile_id,producer_id,role,producer:producers(name)')]); if(profilesError||membersError){setError(profilesError?.message||membersError?.message||'No se pudieron cargar roles.'); setLoading(false); return;} const base=(profiles??[]).map((p:any)=>({profile_id:p.id,role:(p.role||'buyer') as PlatformRole,active:p.active,profile:{full_name:p.full_name},producer_id:null})); const operational=(members??[]).map((m:any)=>({profile_id:m.profile_id,role:(m.role==='owner'?'producer':m.role) as PlatformRole,producer_id:m.producer_id,active:true,profile:base.find((b:any)=>b.profile_id===m.profile_id)?.profile,producer:m.producer})); setAssignments([...base,...operational]); setLoading(false);} load();},[]);
 const counts=roles.map(role=>({role,count:assignments.filter(row=>row.role===role).length}));
 return <section className="container-page py-10"><p className="font-semibold text-red-300">Seguridad</p><h1 className="text-4xl font-black text-white">Roles y permisos</h1><p className="mt-2 max-w-3xl text-white/65">RBAC productivo: todos son compradores por base y pueden sumar roles operativos por productora.</p>{error&&<div className="mt-6 rounded-2xl border border-red-300/30 bg-red-950/40 p-4 text-sm text-red-100">{error}</div>}{loading&&<div className="mt-8 card p-6 text-white/70">Cargando roles reales...</div>}<div className="mt-8 grid gap-4 md:grid-cols-3 xl:grid-cols-6">{counts.map(item=><div key={item.role} className="card p-5"><p className="text-sm text-white/55">{roleLabels[item.role]}</p><p className="mt-2 text-3xl font-black text-white">{item.count}</p></div>)}</div><div className="mt-8 overflow-x-auto rounded-2xl border border-white/10 bg-white/5"><table className="min-w-full text-sm text-white"><thead className="bg-white/10"><tr><th className="p-3 text-left">Permiso</th>{roles.map(role=><th key={role} className="p-3 text-left">{roleLabels[role]}</th>)}</tr></thead><tbody>{permissions.map(permission=><tr key={permission} className="border-t border-white/10"><td className="p-3 font-mono text-xs text-white/75">{permission}</td>{roles.map(role=><td key={role} className="p-3">{rolePermissions[role].includes(permission)?'✅':'—'}</td>)}</tr>)}</tbody></table></div><div className="card mt-8 p-6"><h2 className="text-xl font-black text-white">Asignaciones reales</h2><p className="mt-1 text-sm text-white/55">Perfiles base y roles operativos desde profiles + producer_members.</p><div className="mt-4 overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-sm text-white"><thead className="bg-white/10 text-left text-white/70"><tr><th className="p-3">Usuario</th><th className="p-3">Rol</th><th className="p-3">Productor</th><th className="p-3">Estado</th></tr></thead><tbody>{assignments.map((row,index)=><tr key={`${row.profile_id}-${row.role}-${index}`} className="border-t border-white/10"><td className="p-3"><p className="font-bold">{row.profile?.full_name??row.profile_id}</p><p className="text-xs text-white/50">{row.profile_id}</p></td><td className="p-3"><span className="badge">{roleLabels[row.role]??row.role}</span></td><td className="p-3">{row.producer?.name??'Global'}</td><td className="p-3">{row.active?'Activo':'Inactivo'}</td></tr>)}{!loading&&!assignments.length&&<tr><td className="p-3 text-white/55" colSpan={4}>No hay asignaciones activas.</td></tr>}</tbody></table></div></div></section>
}

export default function RolesPage(){return <AuthGate allow={['super_admin','admin']}><RolesContent/></AuthGate>}
