import Link from 'next/link';
import { Activity, AlertTriangle, CheckCircle2, QrCode, ShieldCheck } from 'lucide-react';
import AuthGate from '@/components/AuthGate';
import { accreditationStats } from '@/lib/platform-config';

function AcreditacionContent(){
 const valid=accreditationStats.reduce((s,r)=>s+r.valid,0);
 const rejected=accreditationStats.reduce((s,r)=>s+r.rejected,0);
 const duplicated=accreditationStats.reduce((s,r)=>s+r.duplicated,0);
 const capacity=accreditationStats.reduce((s,r)=>s+r.capacity,0);
 return <section className="container-page py-10"><p className="font-semibold text-red-300">Ingreso</p><h1 className="text-4xl font-black text-white">Acreditación</h1><p className="mt-2 max-w-3xl text-white/65">Control por QR o código breve, siempre limitado al evento y función seleccionados por el acreditador.</p><div className="mt-8 grid gap-4 md:grid-cols-4"><div className="card p-5"><CheckCircle2 className="text-emerald-200"/><p className="mt-3 text-sm text-white/55">Validados</p><p className="text-3xl font-black text-white">{valid}</p></div><div className="card p-5"><AlertTriangle className="text-red-200"/><p className="mt-3 text-sm text-white/55">Rechazados</p><p className="text-3xl font-black text-white">{rejected}</p></div><div className="card p-5"><Activity className="text-red-200"/><p className="mt-3 text-sm text-white/55">Duplicados</p><p className="text-3xl font-black text-white">{duplicated}</p></div><div className="card p-5"><ShieldCheck className="text-white"/><p className="mt-3 text-sm text-white/55">Capacidad</p><p className="text-3xl font-black text-white">{capacity}</p></div></div><div className="mt-8 grid gap-4 lg:grid-cols-2">{accreditationStats.map(row=><div key={row.eventId} className="card p-6"><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-black text-white">{row.eventName}</h2><p className="mt-1 text-sm text-white/55">{row.gate}</p></div><span className="badge">{Math.round(row.valid/row.capacity*100)}% ingresado</span></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-emerald-400/10 p-4"><p className="text-3xl font-black text-emerald-100">{row.valid}</p><p className="text-xs text-white/55">válidos</p></div><div className="rounded-2xl bg-red-400/10 p-4"><p className="text-3xl font-black text-red-100">{row.rejected}</p><p className="text-xs text-white/55">rechazos</p></div><div className="rounded-2xl bg-white/8 p-4"><p className="text-3xl font-black text-white">{row.duplicated}</p><p className="text-xs text-white/55">repetidos</p></div></div></div>)}</div><div className="mt-8 card p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex items-center gap-2"><QrCode className="text-red-300"/><h2 className="text-xl font-black text-white">Operación del ingreso</h2></div><ul className="mt-4 space-y-2 text-sm text-white/65"><li>• El acreditador ingresa un código de evento o función.</li><li>• El scanner queda bloqueado a ese evento y ese día.</li><li>• Un ticket de otra fecha o evento se rechaza automáticamente.</li><li>• El estado puede ser válido, usado, cancelado o reembolsado.</li></ul></div><Link href="/scanner" className="btn-primary">Abrir scanner</Link></div></div></section>
}
export default function AcreditacionPage(){return <AuthGate allow={['super_admin','admin','producer','accreditor']}><AcreditacionContent/></AuthGate>}
